# platform :ios, '9.0'
use_frameworks!

target 'AquBuy' do

  #ignore all warnings from all pods
  inhibit_all_warnings!

  #Pods for AquBuy
  pod 'FBSDKLoginKit'
  pod 'DownPicker'

  target 'AquBuyTests' do
    inherit! :search_paths
    #Pods for testing
  end

  target 'AquBuyUITests' do
    inherit! :search_paths
    #Pods for testing
  end

end
